# Auto-label PRs based on changed file paths
# Docs: https://github.com/actions/labeler

# App changes in app folder
app:
  - changed-files:
      - any-glob-to-any-file: 'app/**'

# Functions changes in functions folder
functions:
  - changed-files:
      - any-glob-to-any-file: 'functions/**'

# Documentation changes in app/openapi folder or README.md
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
          - 'app/README.md'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

 # Add 'bug' label to any PR where the head branch name starts with `bug` or has a `bug` section in the name
bug:
 - head-branch: ['^bug', 'bug']

  # Add 'improvement' label to any PR where the head branch name starts with `improve` or has a `improve` or `improvement` section in the name
improvement:
 - head-branch: ['^improve', 'improve', 'improvement']
